import { AgentStage } from "../types";

export const INITIAL_STAGES: AgentStage[] = [
  {
    id: "strategy",
    title: "Estratégia & Pauta",
    shortTitle: "Estratégia",
    description: "Análise de métricas, histórico de posts e decisão de pauta com IA.",
    iconType: "strategy",
    status: "pending",
    logs: [],
  },
  {
    id: "content",
    title: "Redação de Conteúdo",
    shortTitle: "Redação",
    description: "Redação técnica multiformato (Carrossel dinâmico, Post Solo, Story ou Reels), gancho, legenda e hashtags.",
    iconType: "content",
    status: "pending",
    logs: [],
  },
  {
    id: "database",
    title: "Persistência PostgreSQL",
    shortTitle: "Banco de Dados",
    description: "Gravação relacional do post e dos slides/cenas no PostgreSQL via Prisma.",
    iconType: "database",
    status: "pending",
    logs: [],
  },
  {
    id: "images",
    title: "Geração de Artes",
    shortTitle: "Artes & Visual",
    description: "Renderização com Recraft AI na identidade dark e ajuste Sharp (Feed 1080x1350 ou Story 1080x1920).",
    iconType: "images",
    status: "pending",
    logs: [],
  },
  {
    id: "storage",
    title: "Armazenamento R2",
    shortTitle: "Storage R2",
    description: "Upload dos buffers das imagens no Cloudflare R2 e vinculação no banco.",
    iconType: "storage",
    status: "pending",
    logs: [],
  },
  {
    id: "review",
    title: "Quality Control (QC)",
    shortTitle: "Revisão QC",
    description: "Auditoria com IA: precisão técnica, hook, engajamento e aprovação (Score ≥ 8.5).",
    iconType: "review",
    status: "pending",
    logs: [],
  },
  {
    id: "finalize",
    title: "Finalização & Pronto",
    shortTitle: "Finalização",
    description: "Validação de integridade e transição de status para READY.",
    iconType: "finalize",
    status: "pending",
    logs: [],
  },
];
